---

name: Upload markdown files
description: Build blog post and uplaod to services like dev.to, medium, etc.

branding:
  icon: arrow-left-circle
  color: green

inputs:
  markdown_file_path:
    description: "The path to the markdown file to convert"
    required: true
  service:
    description: "The service to upload the markdown file to"
    required: true
  key:
    description: "Required key to upload to service"
    required: true
  canonical_url:
    description: "Canonical URL of the blog post"
    required: false
    default: ""
  description:
    description: "Description of the blog post"
    required: false
    default: ""
  publish:
    description: "Publish blog right away"
    required: true
    default: "false"

runs:
  using: composite

  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.X

    - name: Install dependencies
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get code files
      if: inputs.service == "devto"
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python main.py create-devto-blog ${{ markdown_file_path }} ${{ inputs.key }} ${{ inputs.canonical_url }} ${{ inputs.description }} ${{ inputs.publish }}

...
