---

name: Upload markdown files
description: Build blog post and uplaod to services like dev.to, medium, etc.

branding:
  icon: arrow-left-circle
  color: green

inputs:
  articles_map:
    description: "Json datastructure mapping filepaths to artcile ids"
    required: true
  markdown_files_dir:
    description: "The path to the markdown file to convert"
    required: true
  service:
    description: "The service to upload the markdown file to"
    required: true
  gh_pages_repo:
    description: GitHub Pages source url
    required: True
  key:
    description: "Required key to upload to service"
    required: true
  publish:
    description: "Publish blog right away"
    required: true
    default: "false"

runs:
  using: composite

  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.X

    - name: Install dependencies
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get code files
      if: inputs.service == 'Devto'
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        python main.py sync-blog '${{ inputs.articles_map }}' "${{ inputs.markdown_files_dir }}" "${{ inputs.gh_pages_repo }}" "${{ inputs.key }}" "${{ inputs.publish }}"

...
