---

    name: CI

    on:
      push:
        branches:
          - main
        paths-ignore:
          - 'README.md'
          - 'TODO.md'
          - '**/*.md'
          - .gitignore

    env:
      PYTHON_VERSION: "3.12"
    
    jobs:
      pytest:
        runs-on: ubuntu-latest
    
        steps:
          - name: Set up Python ${{ env.PYTHON_VERSION }}
            uses: actions/setup-python@v5
            with:
              python-version: ${{ env.PYTHON_VERSION }}

          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: "main"
              fetch-depth: 0

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            working-directory: ${{ github.workspace }}

          - name: Run unit tests
            run: |
              pytest tests/unittests/
            working-directory: ${{ github.workspace }}

          - name: Run integration tests
            run: |
              pytest tests/integrationtests/
            working-directory: ${{ github.workspace }}
            env:
              DEVTO_API_KEY: ${{ secrets.DEVTO_KEY }}

      smoke-tests:
        needs:
          - pytest
        runs-on: ubuntu-latest

        steps:
          - name: Get random article id
            id: article_id
            run: |
              article_id=$(curl -H "api-key: ${{ secrets.DEVTO_KEY }}" https://dev.to/api/articles/me/unpublished | jq '.[].id' | shuf -n 1)
              echo "article_id=$article_id" >> $GITHUB_OUTPUT

          - name: Create new article
            id: create_article
            run: |
              cat > test_create_article.md <<EOF
              # Smoke test create article

              ## Introduction
              This is a test markdown file for smoke testing article creations.

              ## Code Example
              \`\`\`python
              def hello():
                  print("Hello, Markdown!")
              \`\`\`

              ## Quote
              > "Technology is best when it brings people together."

              ## List of Topics
              - Bash Scripting
              - Python Development
              - DevOps
              EOF

          - name: Update article
            id: update_article
            run: |
              cat > test_update_article.md <<EOF
              # Smoke test update article

              ## Introduction
              This is a test markdown file for smoke testing article updates.

              ## Code Example
              \`\`\`python
              def hello():
                  print("Hello, Updater!")
              \`\`\`

              ## Quote
              > "I was updated."
              EOF

              article_id=$(curl -H "api-key: ${{ secrets.DEVTO_KEY }}" https://dev.to/api/articles/me/unpublished jq --argjson exclude "${{ steps.article_id.outputs.article_id }}" '[.[] | select(.id != ${{ steps.article_id.outputs.article_id }})] | .[].id' | shuf -n 1)
              echo "update_article_id=$article_id" >> $GITHUB_OUTPUT

          - name: Apply changes to articles
            uses: philnewm/blog-upload@main
            with:
              articles_map: '${{ env.article_id_map }}'
              markdown_files_dir: "${{ github.workspace }}/"
              service: "Devto"
              gh_pages_repo: "https://philnewm.github.io/"
              key: ${{ secrets.DEVTO_KEY }}
              publish: False
            env:
              article_id_map: '{"test_update_article.md": "${{ steps.update_article.outputs.update_article_id }}", "test_create_article.md": "", "": ${{ steps.article_id.outputs.article_id }} }'

...
