---

    name: CI
    
    on:
      push:
        branches:
          - main
        paths-ignore:
          - 'README.md'
          - 'TODO.md'
          - '**/*.md'
          - .gitignore
    
    env:
      PYTHON_VERSION: "3.12"
    
    jobs:
      unit-tests:
        runs-on: ubuntu-latest
    
        steps:
          - name: Set up Python ${{ env.PYTHON_VERSION }}
            uses: actions/setup-python@v5
            with:
              python-version: ${{ env.PYTHON_VERSION }}
    
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: "main"
              fetch-depth: 0
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            working-directory: ${{ github.workspace }}
    
          - name: Run unit tests
            run: |
              pytest
            working-directory: ${{ github.workspace }}
    
...
