---

    name: CI
    
    on:
      push:
        branches:
          - main
        paths-ignore:
          - 'README.md'
          - 'TODO.md'
          - '**/*.md'
          - .gitignore
    
    env:
      PYTHON_VERSION: "3.12"
    
    jobs:
      unit-tests:
        runs-on: ubuntu-latest
    
        steps:
          - name: Set up Python ${{ env.PYTHON_VERSION }}
            uses: actions/setup-python@v5
            with:
              python-version: ${{ env.PYTHON_VERSION }}

          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              ref: "main"
              fetch-depth: 0

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            working-directory: ${{ github.workspace }}

          - name: Run unit tests
            run: |
              pytest
            working-directory: ${{ github.workspace }}



      integreatin-tests:
        runs-on: ubuntu-latest

        steps:
          - name: Get markdown files
            run: |
              curl

          - name: Apply changes to articles
            uses: philnewm/blog-upload@main
            with:
              articles_map: ${{ needs.collect-articles.outputs.files_map }}
              markdown_files_dir: "${{ github.workspace }}/tmp/"
              service: "Devto"
              gh_pages_repo: "https://philnewm.github.io/"
              key: ${{ secrets.DEVTO_KEY }}
              publish: False
...
